set(BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/NativeDesktop/")

set(_MINECRAFT_CLIENT_NATIVE_DESKTOP_NATIVE
  "${BASE_DIR}/NativeDesktopClientRuntime.cpp"
  "${BASE_DIR}/NativeDesktopClientApp.h"
  "${BASE_DIR}/NativeDesktopClientStubs.h"
  "${BASE_DIR}/NativeDesktop_UIController.h"
)
source_group("NativeDesktop" FILES ${_MINECRAFT_CLIENT_NATIVE_DESKTOP_NATIVE})

set(MINECRAFT_CLIENT_NATIVE_DESKTOP
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_AUDIO}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_NETWORK}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_COMPONENTS}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_CONTROLS}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_DEBUG}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_FRONTEND_MENU_SCREENS}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_HELP__OPTIONS}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_INGAME_MENU_SCREENS}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_INGAME_MENU_SCREENS_CONTAINERS}
  ${_MINECRAFT_CLIENT_WINDOWS_COMMON_ZLIB}
  ${_MINECRAFT_CLIENT_WINDOWS_PS3_PS3EXTRAS}
  ${_MINECRAFT_CLIENT_WINDOWS_XBOX_NETWORK}
  ${_MINECRAFT_CLIENT_NATIVE_DESKTOP_NATIVE}
)
